/**
 * Comprehensive Delhi NCR & Aerocity Hotel Catalog
 *
 * Provides complete data for Lemon Tree Premier, Delhi Airport (Client Property)
 * and 41 real competitor properties across concentric radius bands:
 * - Aerocity Core (< 1 km)
 * - Delhi Airport & Mahipalpur (1 - 3 km)
 * - Dwarka & Yashobhoomi (3 - 8 km)
 * - Vasant Kunj & South Delhi (3 - 8 km)
 * - Gurugram Cybercity & Udyog Vihar (5 - 12 km)
 * - Central Delhi & Diplomatic Enclave (10 - 15 km)
 */

export interface HotelCatalogItem {
  id: number;
  slug: string;
  name: string;
  shortName: string;
  stars: number;
  distanceKm: number;
  rate: number;
  lat: number;
  lng: number;
  address: string;
  ota: string;
  status: string;
  isUndercut: boolean;
  defaultInSet: boolean;
  zone: string;
}

export const MASTER_HOTELS_CATALOG: HotelCatalogItem[] = [
  // --- 1. AEROCITY CORE (< 1 km) ---
  {
    id: 101,
    slug: "aloft",
    name: "Aloft New Delhi Aerocity",
    shortName: "Aloft Aerocity",
    stars: 5,
    distanceKm: 0.3,
    rate: 8400,
    lat: 28.5518,
    lng: 77.1245,
    address: "Asset 5B, Hospitality District, Aerocity, New Delhi",
    ota: "MakeMyTrip",
    status: "Price Raised (+12%)",
    isUndercut: false,
    defaultInSet: true,
    zone: "Aerocity Core",
  },
  {
    id: 102,
    slug: "holiday_inn",
    name: "Holiday Inn Express Aerocity",
    shortName: "Holiday Inn Aerocity",
    stars: 4,
    distanceKm: 0.3,
    rate: 6900,
    lat: 28.5528,
    lng: 77.1205,
    address: "Asset Area 12, Hospitality District, Aerocity, New Delhi",
    ota: "Booking.com",
    status: "Price Raised (+8%)",
    isUndercut: false,
    defaultInSet: true,
    zone: "Aerocity Core",
  },
  {
    id: 103,
    slug: "novotel",
    name: "Novotel New Delhi Aerocity",
    shortName: "Novotel Aerocity",
    stars: 5,
    distanceKm: 0.3,
    rate: 9200,
    lat: 28.5482,
    lng: 77.1210,
    address: "Asset No 2, Hospitality District, Aerocity, New Delhi",
    ota: "Agoda",
    status: "High Demand (+15%)",
    isUndercut: false,
    defaultInSet: true,
    zone: "Aerocity Core",
  },
  {
    id: 104,
    slug: "pullman",
    name: "Pullman New Delhi Aerocity",
    shortName: "Pullman Aerocity",
    stars: 5,
    distanceKm: 0.3,
    rate: 12800,
    lat: 28.5475,
    lng: 77.1218,
    address: "Asset No 2, Hospitality District, Aerocity, New Delhi",
    ota: "MakeMyTrip",
    status: "High Demand (+10%)",
    isUndercut: false,
    defaultInSet: true,
    zone: "Aerocity Core",
  },
  {
    id: 105,
    slug: "ibis",
    name: "Ibis New Delhi Aerocity",
    shortName: "Ibis Aerocity",
    stars: 3,
    distanceKm: 0.4,
    rate: 4600,
    lat: 28.5470,
    lng: 77.1248,
    address: "Asset No 9, Hospitality District, Aerocity, New Delhi",
    ota: "MakeMyTrip",
    status: "Steady Price (0%)",
    isUndercut: true,
    defaultInSet: true,
    zone: "Aerocity Core",
  },
  {
    id: 106,
    slug: "jw_marriott",
    name: "JW Marriott Hotel New Delhi Aerocity",
    shortName: "JW Marriott Aerocity",
    stars: 5,
    distanceKm: 0.3,
    rate: 14500,
    lat: 28.5522,
    lng: 77.1188,
    address: "Asset Area 4 - Hospitality District, Aerocity, New Delhi",
    ota: "MakeMyTrip",
    status: "High Demand (+14%)",
    isUndercut: false,
    defaultInSet: false,
    zone: "Aerocity Core",
  },
  {
    id: 107,
    slug: "roseate_house",
    name: "Roseate House New Delhi",
    shortName: "Roseate House",
    stars: 5,
    distanceKm: 0.3,
    rate: 13200,
    lat: 28.5492,
    lng: 77.1190,
    address: "Asset 10, Hospitality District, Aerocity, New Delhi",
    ota: "Booking.com",
    status: "Steady (+2%)",
    isUndercut: false,
    defaultInSet: false,
    zone: "Aerocity Core",
  },
  {
    id: 108,
    slug: "andaz_delhi",
    name: "Andaz Delhi (by Hyatt)",
    shortName: "Andaz Delhi",
    stars: 5,
    distanceKm: 0.4,
    rate: 12900,
    lat: 28.5540,
    lng: 77.1228,
    address: "Asset No.1, Northern Access Rd, Aerocity, New Delhi",
    ota: "Agoda",
    status: "High Demand (+9%)",
    isUndercut: false,
    defaultInSet: false,
    zone: "Aerocity Core",
  },
  {
    id: 109,
    slug: "pride_plaza",
    name: "Pride Plaza Hotel Aerocity",
    shortName: "Pride Plaza Aerocity",
    stars: 5,
    distanceKm: 0.4,
    rate: 6400,
    lat: 28.5485,
    lng: 77.1255,
    address: "Asset 5A, Hospitality District, Aerocity, New Delhi",
    ota: "MakeMyTrip",
    status: "Similar Price (+4%)",
    isUndercut: false,
    defaultInSet: false,
    zone: "Aerocity Core",
  },
  {
    id: 110,
    slug: "red_fox",
    name: "Red Fox Hotel Delhi Airport",
    shortName: "Red Fox Aerocity",
    stars: 3,
    distanceKm: 0.2,
    rate: 4200,
    lat: 28.5502,
    lng: 77.1228,
    address: "Asset No. 6, Aerocity Hospitality District, New Delhi",
    ota: "MakeMyTrip",
    status: "Budget Alternative (-27%)",
    isUndercut: true,
    defaultInSet: false,
    zone: "Aerocity Core",
  },
  {
    id: 111,
    slug: "ibis_styles",
    name: "ibis Styles New Delhi Aerocity",
    shortName: "Ibis Styles",
    stars: 3,
    distanceKm: 0.6,
    rate: 4900,
    lat: 28.5462,
    lng: 77.1260,
    address: "Asset 9B, Aerocity Hospitality District, New Delhi",
    ota: "Booking.com",
    status: "Economy Option (-15%)",
    isUndercut: true,
    defaultInSet: false,
    zone: "Aerocity Core",
  },

  // --- 2. DELHI AIRPORT & MAHIPALPUR (1 - 3 km) ---
  {
    id: 112,
    slug: "radisson_blu",
    name: "Radisson Blu Plaza Delhi Airport",
    shortName: "Radisson Blu Airport",
    stars: 5,
    distanceKm: 1.1,
    rate: 8100,
    lat: 28.5448,
    lng: 77.1292,
    address: "NH-48, near Delhi Airport, Mahipalpur, New Delhi",
    ota: "Booking.com",
    status: "Price Raised (+6%)",
    isUndercut: false,
    defaultInSet: false,
    zone: "Airport & Mahipalpur",
  },
  {
    id: 113,
    slug: "four_points",
    name: "Four Points by Sheraton Delhi Airport",
    shortName: "Four Points Airport",
    stars: 4,
    distanceKm: 2.5,
    rate: 5900,
    lat: 28.5320,
    lng: 77.1080,
    address: "Plot No 9, National Highway - 8, Samalka, New Delhi",
    ota: "Agoda",
    status: "Steady Price (0%)",
    isUndercut: false,
    defaultInSet: false,
    zone: "Airport & Mahipalpur",
  },
  {
    id: 114,
    slug: "shanti_palace",
    name: "Hotel Shanti Palace Mahipalpur",
    shortName: "Shanti Palace",
    stars: 3,
    distanceKm: 1.4,
    rate: 3200,
    lat: 28.5440,
    lng: 77.1330,
    address: "A-4, Mahipalpur Bypass, Vasant Kunj Rd, New Delhi",
    ota: "MakeMyTrip",
    status: "Budget Airport Hotel",
    isUndercut: true,
    defaultInSet: false,
    zone: "Airport & Mahipalpur",
  },
  {
    id: 115,
    slug: "classic_diplomat",
    name: "Hotel Classic Diplomat Delhi",
    shortName: "Classic Diplomat",
    stars: 3,
    distanceKm: 1.5,
    rate: 3100,
    lat: 28.5425,
    lng: 77.1345,
    address: "NH-8, Mahipalpur Extension, New Delhi",
    ota: "Agoda",
    status: "Budget Transit Hotel",
    isUndercut: true,
    defaultInSet: false,
    zone: "Airport & Mahipalpur",
  },
  {
    id: 116,
    slug: "hotel_aerotech",
    name: "Hotel Aerotech Delhi Airport",
    shortName: "Hotel Aerotech",
    stars: 3,
    distanceKm: 1.7,
    rate: 2800,
    lat: 28.5410,
    lng: 77.1360,
    address: "Near IGI Airport, Mahipalpur Bypass, New Delhi",
    ota: "Booking.com",
    status: "Budget Transit Hotel",
    isUndercut: true,
    defaultInSet: false,
    zone: "Airport & Mahipalpur",
  },
  {
    id: 117,
    slug: "smart_signature",
    name: "Hotel Smart Signature Aerocity Bypass",
    shortName: "Smart Signature",
    stars: 3,
    distanceKm: 1.8,
    rate: 2600,
    lat: 28.5395,
    lng: 77.1350,
    address: "Block A, Mahipalpur Near Aerocity Metro, New Delhi",
    ota: "MakeMyTrip",
    status: "Budget Alternative",
    isUndercut: true,
    defaultInSet: false,
    zone: "Airport & Mahipalpur",
  },
  {
    id: 118,
    slug: "hotel_marina",
    name: "Airport Hotel Marina Mahipalpur",
    shortName: "Airport Hotel Marina",
    stars: 3,
    distanceKm: 1.7,
    rate: 2400,
    lat: 28.5435,
    lng: 77.1315,
    address: "Opposite Aerocity Gate 2, Mahipalpur, New Delhi",
    ota: "Agoda",
    status: "Budget Transit Hotel",
    isUndercut: true,
    defaultInSet: false,
    zone: "Airport & Mahipalpur",
  },
  {
    id: 119,
    slug: "the_umrao",
    name: "The Umrao Luxury Resort",
    shortName: "The Umrao",
    stars: 5,
    distanceKm: 2.9,
    rate: 7200,
    lat: 28.5210,
    lng: 77.0980,
    address: "National Highway 8, Rajokri, New Delhi",
    ota: "MakeMyTrip",
    status: "Boutique Resort (+24%)",
    isUndercut: false,
    defaultInSet: false,
    zone: "Airport & Mahipalpur",
  },
  {
    id: 120,
    slug: "atrio_boutique",
    name: "Atrio - A Boutique Hotel",
    shortName: "Atrio Boutique",
    stars: 4,
    distanceKm: 2.7,
    rate: 4800,
    lat: 28.5260,
    lng: 77.1020,
    address: "Rajokri, Near Aerocity, NH-8, New Delhi",
    ota: "Booking.com",
    status: "Boutique Hotel (-17%)",
    isUndercut: true,
    defaultInSet: false,
    zone: "Airport & Mahipalpur",
  },

  // --- 3. DWARKA & YASHOBHOOMI CONVENTION CORRIDOR (3 - 8 km) ---
  {
    id: 121,
    slug: "vivanta_dwarka",
    name: "Vivanta New Delhi, Dwarka",
    shortName: "Vivanta Dwarka",
    stars: 5,
    distanceKm: 6.8,
    rate: 7600,
    lat: 28.5830,
    lng: 77.0620,
    address: "Near Sector 21 Metro, Dwarka (near Yashobhoomi)",
    ota: "MakeMyTrip",
    status: "High Demand (+18%)",
    isUndercut: false,
    defaultInSet: false,
    zone: "Dwarka & Yashobhoomi",
  },
  {
    id: 122,
    slug: "welcomhotel_dwarka",
    name: "Welcomhotel by ITC Hotels, Dwarka",
    shortName: "Welcomhotel Dwarka",
    stars: 5,
    distanceKm: 7.4,
    rate: 7900,
    lat: 28.5890,
    lng: 77.0540,
    address: "District Centre, Sector 10, Dwarka, New Delhi",
    ota: "Booking.com",
    status: "Expo Spillover Demand",
    isUndercut: false,
    defaultInSet: false,
    zone: "Dwarka & Yashobhoomi",
  },
  {
    id: 123,
    slug: "radisson_dwarka",
    name: "Radisson Blu Hotel New Delhi Dwarka",
    shortName: "Radisson Blu Dwarka",
    stars: 5,
    distanceKm: 8.1,
    rate: 8200,
    lat: 28.5940,
    lng: 77.0420,
    address: "Plot 4, Sector 13, Dwarka, New Delhi",
    ota: "Agoda",
    status: "Corporate Demand (+12%)",
    isUndercut: false,
    defaultInSet: false,
    zone: "Dwarka & Yashobhoomi",
  },
  {
    id: 124,
    slug: "treebo_dwarka",
    name: "Treebo Trend Dwarka Residency",
    shortName: "Treebo Dwarka",
    stars: 3,
    distanceKm: 7.8,
    rate: 2900,
    lat: 28.5880,
    lng: 77.0480,
    address: "Sector 12, Dwarka, New Delhi",
    ota: "MakeMyTrip",
    status: "Budget Option",
    isUndercut: true,
    defaultInSet: false,
    zone: "Dwarka & Yashobhoomi",
  },

  // --- 4. VASANT KUNJ & SOUTH DELHI (3 - 8 km) ---
  {
    id: 125,
    slug: "the_grand",
    name: "The Grand New Delhi",
    shortName: "The Grand New Delhi",
    stars: 5,
    distanceKm: 4.2,
    rate: 11200,
    lat: 28.5410,
    lng: 77.1550,
    address: "Nelson Mandela Road, Vasant Kunj, New Delhi",
    ota: "MakeMyTrip",
    status: "Luxury Resort (+93%)",
    isUndercut: false,
    defaultInSet: false,
    zone: "Vasant Kunj",
  },
  {
    id: 126,
    slug: "the_uppal",
    name: "The Uppal - An Ecotel Hotel",
    shortName: "The Uppal Ecotel",
    stars: 4,
    distanceKm: 3.8,
    rate: 5400,
    lat: 28.5300,
    lng: 77.1350,
    address: "Near IGI Airport, NH-8, Dhaula Kuan Extension, New Delhi",
    ota: "Agoda",
    status: "Eco Hotel (-7%)",
    isUndercut: true,
    defaultInSet: false,
    zone: "Vasant Kunj",
  },
  {
    id: 127,
    slug: "jaypee_vasant",
    name: "Jaypee Vasant Continental",
    shortName: "Jaypee Vasant Continental",
    stars: 5,
    distanceKm: 5.5,
    rate: 9800,
    lat: 28.5580,
    lng: 77.1620,
    address: "Basant Lok, Vasant Vihar, New Delhi",
    ota: "Booking.com",
    status: "Diplomatic Demand (+68%)",
    isUndercut: false,
    defaultInSet: false,
    zone: "Vasant Kunj",
  },
  {
    id: 128,
    slug: "hyatt_regency",
    name: "Hyatt Regency Delhi",
    shortName: "Hyatt Regency Delhi",
    stars: 5,
    distanceKm: 7.9,
    rate: 12500,
    lat: 28.5680,
    lng: 77.1850,
    address: "Bhikaji Cama Place, Ring Road, New Delhi",
    ota: "MakeMyTrip",
    status: "Luxury Commercial (+115%)",
    isUndercut: false,
    defaultInSet: false,
    zone: "South Delhi",
  },

  // --- 5. GURUGRAM CYBERCITY / UDYOG VIHAR / NH-48 (5 - 12 km) ---
  {
    id: 129,
    slug: "leela_gurgaon",
    name: "The Leela Ambience Gurugram",
    shortName: "Leela Ambience Gurgaon",
    stars: 5,
    distanceKm: 5.8,
    rate: 15500,
    lat: 28.5030,
    lng: 77.0970,
    address: "Ambience Island, National Highway 8, Gurugram",
    ota: "Booking.com",
    status: "Cybercity Hub (+167%)",
    isUndercut: false,
    defaultInSet: false,
    zone: "Gurugram Cybercity",
  },
  {
    id: 130,
    slug: "hyatt_place_gurgaon",
    name: "Hyatt Place Gurgaon Udyog Vihar",
    shortName: "Hyatt Place Gurgaon",
    stars: 4,
    distanceKm: 6.2,
    rate: 6800,
    lat: 28.5010,
    lng: 77.0850,
    address: "15/1, Old Delhi-Gurgaon Rd, Udyog Vihar, Gurugram",
    ota: "Agoda",
    status: "Business Hotel (+17%)",
    isUndercut: false,
    defaultInSet: false,
    zone: "Gurugram Cybercity",
  },
  {
    id: 131,
    slug: "oberoi_gurgaon",
    name: "The Oberoi, Gurgaon",
    shortName: "The Oberoi Gurgaon",
    stars: 5,
    distanceKm: 6.5,
    rate: 19800,
    lat: 28.4980,
    lng: 77.0890,
    address: "443, Udyog Vihar Phase V, Gurugram",
    ota: "MakeMyTrip",
    status: "Ultra Luxury Tier",
    isUndercut: false,
    defaultInSet: false,
    zone: "Gurugram Cybercity",
  },
  {
    id: 132,
    slug: "trident_gurgaon",
    name: "Trident Hotel Gurgaon",
    shortName: "Trident Gurgaon",
    stars: 5,
    distanceKm: 6.6,
    rate: 14200,
    lat: 28.4970,
    lng: 77.0880,
    address: "443, Udyog Vihar Phase V, Gurugram",
    ota: "Booking.com",
    status: "Luxury Business (+144%)",
    isUndercut: false,
    defaultInSet: false,
    zone: "Gurugram Cybercity",
  },
  {
    id: 133,
    slug: "lemontree_gurgaon",
    name: "Lemon Tree Hotel, Udyog Vihar",
    shortName: "Lemon Tree Udyog Vihar",
    stars: 4,
    distanceKm: 6.8,
    rate: 5100,
    lat: 28.4960,
    lng: 77.0820,
    address: "Phase 4, Udyog Vihar, Gurugram",
    ota: "MakeMyTrip",
    status: "Sister Property (-12%)",
    isUndercut: true,
    defaultInSet: false,
    zone: "Gurugram Cybercity",
  },
  {
    id: 134,
    slug: "radisson_gurgaon",
    name: "Radisson Gurugram Udyog Vihar",
    shortName: "Radisson Gurugram",
    stars: 4,
    distanceKm: 7.1,
    rate: 6100,
    lat: 28.4930,
    lng: 77.0840,
    address: "Plot No 406, Phase III, Udyog Vihar, Gurugram",
    ota: "Agoda",
    status: "Corporate Corridor (+5%)",
    isUndercut: false,
    defaultInSet: false,
    zone: "Gurugram Cybercity",
  },
  {
    id: 135,
    slug: "westin_gurgaon",
    name: "The Westin Gurgaon, New Delhi",
    shortName: "The Westin Gurgaon",
    stars: 5,
    distanceKm: 8.9,
    rate: 16400,
    lat: 28.4780,
    lng: 77.0720,
    address: "Number 1, MG Road, Sector 29, Gurugram",
    ota: "MakeMyTrip",
    status: "High Luxury Demand",
    isUndercut: false,
    defaultInSet: false,
    zone: "Gurugram Cybercity",
  },
  {
    id: 136,
    slug: "courtyard_gurgaon",
    name: "Courtyard by Marriott Gurugram Downtown",
    shortName: "Courtyard Gurugram",
    stars: 4,
    distanceKm: 9.8,
    rate: 8700,
    lat: 28.4650,
    lng: 77.0710,
    address: "B Block, Sushant Lok Phase I, Gurugram",
    ota: "Booking.com",
    status: "Steady Demand (+50%)",
    isUndercut: false,
    defaultInSet: false,
    zone: "Gurugram",
  },
  {
    id: 137,
    slug: "crowne_plaza_gurgaon",
    name: "Crowne Plaza Today Gurugram",
    shortName: "Crowne Plaza Gurgaon",
    stars: 5,
    distanceKm: 10.2,
    rate: 9500,
    lat: 28.4680,
    lng: 77.0620,
    address: "Sector 29, National Highway 8, Gurugram",
    ota: "Agoda",
    status: "Convention Hotel (+63%)",
    isUndercut: false,
    defaultInSet: false,
    zone: "Gurugram",
  },

  // --- 6. CENTRAL DELHI & DIPLOMATIC ENCLAVE (10 - 15 km) ---
  {
    id: 138,
    slug: "taj_palace",
    name: "Taj Palace, New Delhi",
    shortName: "Taj Palace Delhi",
    stars: 5,
    distanceKm: 11.5,
    rate: 18200,
    lat: 28.5950,
    lng: 77.1720,
    address: "2 Sardar Patel Marg, Diplomatic Enclave, New Delhi",
    ota: "MakeMyTrip",
    status: "Diplomatic Peak (+213%)",
    isUndercut: false,
    defaultInSet: false,
    zone: "Central Delhi",
  },
  {
    id: 139,
    slug: "itc_maurya",
    name: "ITC Maurya, a Luxury Collection Hotel",
    shortName: "ITC Maurya",
    stars: 5,
    distanceKm: 11.8,
    rate: 19500,
    lat: 28.5970,
    lng: 77.1740,
    address: "Diplomatic Enclave, Sardar Patel Marg, New Delhi",
    ota: "Booking.com",
    status: "VVIP Dignitary Demand",
    isUndercut: false,
    defaultInSet: false,
    zone: "Central Delhi",
  },
  {
    id: 140,
    slug: "leela_palace_delhi",
    name: "The Leela Palace New Delhi",
    shortName: "The Leela Palace Delhi",
    stars: 5,
    distanceKm: 12.5,
    rate: 22000,
    lat: 28.5800,
    lng: 77.1900,
    address: "Diplomatic Enclave, Chanakyapuri, New Delhi",
    ota: "MakeMyTrip",
    status: "Ultra Luxury Tier",
    isUndercut: false,
    defaultInSet: false,
    zone: "Central Delhi",
  },
  {
    id: 141,
    slug: "claridges_delhi",
    name: "The Claridges New Delhi",
    shortName: "The Claridges",
    stars: 5,
    distanceKm: 14.2,
    rate: 16800,
    lat: 28.6010,
    lng: 77.2180,
    address: "12 Dr APJ Abdul Kalam Road, New Delhi",
    ota: "Agoda",
    status: "Heritage Luxury",
    isUndercut: false,
    defaultInSet: false,
    zone: "Central Delhi",
  },
];

/**
 * Returns a clean, consistent short name for display on badges, tables, and chips
 */
export const getShortName = (fullName: string): string => {
  if (!fullName) return "";
  const match = MASTER_HOTELS_CATALOG.find(
    (h) =>
      h.name.toLowerCase() === fullName.toLowerCase() ||
      h.shortName.toLowerCase() === fullName.toLowerCase() ||
      fullName.toLowerCase().includes(h.shortName.toLowerCase()) ||
      h.name.toLowerCase().includes(fullName.toLowerCase())
  );
  if (match) return match.shortName;

  if (fullName.includes("Aloft")) return "Aloft Aerocity";
  if (fullName.includes("Holiday")) return "Holiday Inn Aerocity";
  if (fullName.includes("Novotel")) return "Novotel Aerocity";
  if (fullName.includes("Pullman")) return "Pullman Aerocity";
  if (fullName.includes("Ibis") && !fullName.includes("Styles")) return "Ibis Aerocity";
  if (fullName.includes("Styles")) return "Ibis Styles";
  if (fullName.includes("JW Marriott") || fullName.includes("Marriott Aerocity")) return "JW Marriott Aerocity";
  if (fullName.includes("Roseate")) return "Roseate House";
  if (fullName.includes("Andaz")) return "Andaz Delhi";
  if (fullName.includes("Pride Plaza")) return "Pride Plaza Aerocity";
  if (fullName.includes("Red Fox")) return "Red Fox Aerocity";
  if (fullName.includes("Radisson Blu Plaza") || fullName.includes("Radisson Blu Airport")) return "Radisson Blu Airport";
  if (fullName.includes("Four Points")) return "Four Points Airport";
  if (fullName.includes("Shanti Palace")) return "Shanti Palace";
  if (fullName.includes("Classic Diplomat")) return "Classic Diplomat";
  if (fullName.includes("Aerotech")) return "Hotel Aerotech";
  if (fullName.includes("Smart Signature")) return "Smart Signature";
  if (fullName.includes("Marina")) return "Airport Hotel Marina";
  if (fullName.includes("Umrao")) return "The Umrao";
  if (fullName.includes("Atrio")) return "Atrio Boutique";
  if (fullName.includes("Vivanta")) return "Vivanta Dwarka";
  if (fullName.includes("Welcomhotel") || fullName.includes("ITC Dwarka")) return "Welcomhotel Dwarka";
  if (fullName.includes("Dwarka") && fullName.includes("Radisson")) return "Radisson Blu Dwarka";
  if (fullName.includes("Treebo")) return "Treebo Dwarka";
  if (fullName.includes("Grand New Delhi")) return "The Grand New Delhi";
  if (fullName.includes("Uppal")) return "The Uppal Ecotel";
  if (fullName.includes("Jaypee Vasant")) return "Jaypee Vasant Continental";
  if (fullName.includes("Hyatt Regency")) return "Hyatt Regency Delhi";
  if (fullName.includes("Leela Ambience")) return "Leela Ambience Gurgaon";
  if (fullName.includes("Hyatt Place")) return "Hyatt Place Gurgaon";
  if (fullName.includes("Oberoi")) return "The Oberoi Gurgaon";
  if (fullName.includes("Trident")) return "Trident Gurgaon";
  if (fullName.includes("Udyog Vihar") && fullName.includes("Lemon Tree")) return "Lemon Tree Udyog Vihar";
  if (fullName.includes("Radisson Gurugram")) return "Radisson Gurugram";
  if (fullName.includes("Westin")) return "The Westin Gurgaon";
  if (fullName.includes("Courtyard")) return "Courtyard Gurugram";
  if (fullName.includes("Crowne Plaza")) return "Crowne Plaza Gurgaon";
  if (fullName.includes("Taj Palace")) return "Taj Palace Delhi";
  if (fullName.includes("ITC Maurya")) return "ITC Maurya";
  if (fullName.includes("Leela Palace")) return "The Leela Palace Delhi";
  if (fullName.includes("Claridges")) return "The Claridges";
  return fullName;
};
